replicas: 2

image:
  repository: ghcr.io/kakaotech-19/kakaotech-19/ai-music
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP # ClusterIP 또는 LoadBalancer 또는 NodePort 로 변경 가능
  port: 5003

# Resource Limit
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
