replicaCount: 2

image:
  repository: ghcr.io/kakaotech-19/kakaotech-19/ai-text
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: ENVIRONMENT
    value: "production"
