apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret # AWS Secret Manager에서 관리하는 민감 정보 가져오는 용도.
metadata:
  name: my-secret
  namespace: dev # 이후 prod 환경도 고려 할 수 있게끔 변경 필요.
spec:
  refreshInterval: "1h" # 비밀 데이터 동기화 주기
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: aws-todak-secret
    creationPolicy: Owner
  data:
    - secretKey: AI_IMAGE_OPENAPI_KEY
      remoteRef:
        key: todaktodak-secret
        property: AI_IMAGE_OPENAPI_KEY
    - secretKey: AI_AWS_ACCESS_KEY_ID
      remoteRef:
        key: todaktodak-secret
        property: AI_AWS_ACCESS_KEY_ID
    - secretKey: AI_AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: todaktodak-secret
        property: AI_AWS_SECRET_ACCESS_KEY
    - secretKey: AI_IMAGE_REPLICATE_API_TOKEN
      remoteRef:
        key: todaktodak-secret
        property: AI_IMAGE_REPLICATE_API_TOKEN
    - secretKey: AI_MUSIC_REPLICATE_API_TOKEN
      remoteRef:
        key: todaktodak-secret
        property: AI_MUSIC_REPLICATE_API_TOKEN
    - secretKey: AI_MUSIC_OPENAI_API_KEY
      remoteRef:
        key: todaktodak-secret
        property: AI_MUSIC_OPENAI_API_KEY
    - secretKey: AI_TEXT_OPENAI_KEY
      remoteRef:
        key: todaktodak-secret
        property: AI_TEXT_OPENAI_KEY
    - secretKey: BACKEND_POSTGRESQL_PASSWORD
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_POSTGRESQL_PASSWORD
    - secretKey: BACKEND_POSTGRESQL_USER
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_POSTGRESQL_USER
    - secretKey: BACKEND_JWT_SECRET_KEY
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_JWT_SECRET_KEY
    - secretKey: BACKEND_KAKAO_OAUTH_CLIENT_ID
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_KAKAO_OAUTH_CLIENT_ID
    - secretKey: BACKEND_KAKAO_OAUTH_CLIENT_SECRET
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_KAKAO_OAUTH_CLIENT_SECRET
    - secretKey: BACKEND_NAVER_OAUTH_CLIENT_ID
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_NAVER_OAUTH_CLIENT_ID
    - secretKey: BACKEND_NAVER_OAUTH_CLIENT_SECRET
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_NAVER_OAUTH_CLIENT_SECRET
    - secretKey: BACKEND_GOOGLE_OAUTH_CLIENT_ID
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_GOOGLE_OAUTH_CLIENT_ID
    - secretKey: BACKEND_GOOGLE_OAUTH_CLIENT_SECRET
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_GOOGLE_OAUTH_CLIENT_SECRET
    - secretKey: BACKEND_AWS_ACCESS_KEY
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_AWS_ACCESS_KEY
    - secretKey: BACKEND_AWS_SECRET_KEY
      remoteRef:
        key: todaktodak-secret
        property: BACKEND_AWS_SECRET_KEY