apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # AWS Secret Manager 사용 하기 위한 IRSA 연동 용도.
metadata:
  name: "aws-secrets"
  namespace: "external-secrets"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: "external-secrets-sa"
            namespace: "external-secrets"