replicas: 2

image:
  repository: ghcr.io/kakaotech-19/kakaotech-19/ai-image
#  repository: hanyohan/ai-test-app # 테스트용
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer # ClusterIP 또는 LoadBalancer 또는 NodePort 로 변경 가능
  port: 5001

# Resource Limit
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

