replicas: 2

image:
  repository: hanyohan/ai-test-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP # LoadBalancer 또는 NodePort로 변경 가능

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
