apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  AWS_REGION: "ap-northeast-2"
  BUCKET_NAME: "kakaotech19-todak"
  HOST: "0.0.0.0"
  PORT: "5001"
