apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  AWS_S3_BUCKET_NAME: "kakaotech19-todak"
  AWS_S3_REGION: "ap-northeast-2"
  DEFAULT_WEBHOOK_URL: "http://backend:8080/api/v1/webhook/ai/bgm"
