replicaCount: 2

image:
  repository: hanyohan/back-test-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
  host: a813c2fe7207c4add8e3e5bbb94ba114-337815044.ap-northeast-2.elb.amazonaws.com

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

nodeSelector: {}
tolerations: []
affinity: {}
