replicaCount: 2

image:
  repository: ghcr.io/kakaotech-19/kakaotech-19/todaktodak-api
  pullPolicy: Always
  tag: "latest"

# cluster ip타입의 내부도메인 형태 http://backend.default.svc.cluster.local:8080/api/v1
service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 2000m # 최대 2 코어
    memory: 2Gi # 최대 2Gi 메모리
  requests:
    cpu: 1000m # 최소 1 코어
    memory: 1Gi # 최소 1Gi 메모리

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
