name: Cloud Repository CD

on:
  workflow_dispatch: # 외부 트리거 허용
    inputs:
      source_repo:
        description: "Name of the source repository triggering this workflow"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CD_AWS_REGION }}

      # 3. Set up kubectl to connect to the EKS cluster
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.CD_AWS_REGION }} --name ${{ secrets.CD_EKS_CLUSTER_NAME }}

      # 4. Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | VERIFY_CHECKSUM=false bash

      # 5. Helm upgrade or install
      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ github.event.inputs.source_repo }} helm/${{ github.event.inputs.source_repo }} \
            -n dev \
            --create-namespace \
            --history-max 3
