replicaCount: 2

image:
  repository: hanyohan/react-test-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: aa64dddc542a047cc9ff55fbf673ea45-814616462.ap-northeast-2.elb.amazonaws.com

  pathType: Prefix
  annotations: {}

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}